import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { run } from '../src/process.js';
import { defaults, discover, CONFIG } from '../src/config.js';
import { runDefaultHook, installDefaultHook } from '../src/default-hook.js';

test('Git discovery respects nested ignores, negation, tracked files and active subtree', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'quality-ignore-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  run('git', ['init', '--quiet'], root);
  fs.mkdirSync(path.join(root, 'nested'));
  fs.writeFileSync(path.join(root, '.gitignore'), 'ignored.py\n');
  fs.writeFileSync(path.join(root, 'ignored.py'), 'broken syntax');
  fs.writeFileSync(path.join(root, 'tracked.py'), 'x = 1');
  run('git', ['add', 'tracked.py'], root);
  fs.writeFileSync(path.join(root, '.gitignore'), 'ignored.py\ntracked.py\n');
  fs.writeFileSync(path.join(root, 'nested/.gitignore'), '*.py\n!keep.py\n');
  fs.writeFileSync(path.join(root, 'nested/keep.py'), 'x = 1');
  fs.writeFileSync(path.join(root, 'nested/drop.py'), 'broken syntax');
  const files = discover(root, ['**/.git/**']);
  assert.ok(files.includes('tracked.py'));
  assert.ok(files.includes('nested/keep.py'));
  assert.ok(!files.includes('ignored.py') && !files.includes('nested/drop.py'));
  assert.deepEqual(discover(path.join(root, 'nested'), []), ['.gitignore', 'keep.py']);
});

test('default hook isolates worktrees, respects local hooks and supports enforce/off', async t => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), 'quality-worktree-'));
  t.after(() => fs.rmSync(parent, { recursive: true, force: true }));
  const root = path.join(parent, 'repo'), second = path.join(parent, 'second');
  fs.mkdirSync(root);
  run('git', ['init', '--quiet'], root);
  fs.writeFileSync(path.join(root, 'sample.py'), 'def work():\n    return 1\n');
  const config = defaults(root); config.checks.pythonLint = false; config.checks.pythonTypes = false;
  fs.writeFileSync(path.join(root, CONFIG), JSON.stringify(config));
  run('git', ['add', '.'], root);
  assert.equal(run('git', ['-c', 'core.hooksPath=', '-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '-qm', 'fixture'], root).status, 0);
  assert.equal(run('git', ['worktree', 'add', '--detach', second], root).status, 0);
  fs.writeFileSync(path.join(second, 'sample.py'), 'def work():\n    return 1\n    print("unreachable")\n');
  assert.equal(await runDefaultHook(root), 0);
  assert.equal(await runDefaultHook(second), 0);
  const firstReport = JSON.parse(fs.readFileSync(path.join(root, '.git/sloppy/report.json')));
  const location = run('git', ['rev-parse', '--path-format=absolute', '--git-path', 'sloppy'], second).stdout.trim();
  const secondReport = JSON.parse(fs.readFileSync(path.join(location, 'report.json')));
  assert.equal(firstReport.root, root);
  assert.equal(secondReport.root, second);
  assert.equal(firstReport.summary.errors, 0);
  assert.equal(secondReport.summary.errors, 1);
  run('git', ['config', 'sloppy.mode', 'enforce'], root);
  assert.equal(await runDefaultHook(second), 1);
  fs.writeFileSync(path.join(root, '.git/hooks/pre-commit'), '#!/bin/sh\nexit 7\n');
  assert.equal(await runDefaultHook(second), 7);
  fs.unlinkSync(path.join(root, '.git/hooks/pre-commit'));
  run('git', ['config', 'sloppy.mode', 'off'], root);
  assert.equal(await runDefaultHook(second), 0);
});

test('installed dispatcher runs on real commits and preserves configured global hooks', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'quality-dispatch-'));
  const previous = process.env.GIT_CONFIG_GLOBAL;
  process.env.GIT_CONFIG_GLOBAL = path.join(root, 'global-config');
  t.after(() => { if (previous === undefined) delete process.env.GIT_CONFIG_GLOBAL; else process.env.GIT_CONFIG_GLOBAL = previous; fs.rmSync(root, { recursive: true, force: true }); });
  const directory = installDefaultHook();
  assert.equal(installDefaultHook(), directory);
  run('git', ['init', '--quiet'], root);
  fs.writeFileSync(path.join(root, 'sample.py'), 'def work():\n    return 1\n    print("dead")\n');
  const config = defaults(root); config.checks.pythonLint = false; config.checks.pythonTypes = false;
  fs.writeFileSync(path.join(root, CONFIG), JSON.stringify(config));
  run('git', ['add', 'sample.py', CONFIG], root);
  const commit = run('git', ['-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '-qm', 'advisory'], root);
  assert.equal(commit.status, 0, commit.stderr);
  assert.match(commit.stderr, /sloppy \(advisory\): FAIL/);
  assert.ok(fs.existsSync(path.join(root, '.git/sloppy/repair-plan.json')));
  run('git', ['config', 'sloppy.mode', 'enforce'], root);
  const blocked = run('git', ['-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '--allow-empty', '-qm', 'blocked'], root);
  assert.notEqual(blocked.status, 0);
  assert.match(blocked.stderr, /sloppy \(enforce\): FAIL/);
  run('git', ['config', '--global', 'core.hooksPath', path.join(root, 'custom-hooks')], root);
  assert.throws(() => installDefaultHook(), /Existing global hooksPath preserved/);
});
